# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171218_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u6458\u8981'),
        ),
    ]
